# -*- coding: utf-8 -*-
"""Features_Heartpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iiHP_F4mDMhuR3VFSz49AUx_rIHp7q4n
"""

import heartpy as hp
import pandas as pd

# 1. Caricamento dati
path_file = '230426 prova 2.csv'
df = pd.read_csv(path_file)

# Sostituisci 'signal' con il nome reale della tua colonna pre-filtrata
signal_data = df['Final_Result'].values

# 2. Parametri
fs = 200.0

try:
    # 3. Analisi Diretta
    # Usiamo direttamente hp.process senza passare per hp.filter_signal
    # Il parametro report_time=False serve solo a non stampare il tempo di calcolo
    wd, m = hp.process(signal_data, sample_rate=fs)

    # 4. Estrazione Feature (Stampa Formattata)
    bpm_medio = m['bpm']
    ibi_medio = m['ibi']
    sdnn = m['sdnn']
    rmssd = m['rmssd']

    # Battiti totali al netto di quelli eventualmente scartati da HeartPy
    # perché non conformi alla media (outlier residui)
    battiti_totali = len(wd['peaklist']) - len(wd['removed_beats'])

    print(f"BPM Medio:      {bpm_medio:.2f}")
    print(f"RR Medio (IBI): {ibi_medio:.2f} ms")
    print(f"SDNN:           {sdnn:.2f} ms")
    print(f"RMSSD:          {rmssd:.2f} ms")
    print(f"Battiti Totali: {battiti_totali}")

    # 5. Visualizzazione (Consigliata per verificare la corretta rilevazione dei picchi)
    hp.plotter(wd, m)

except Exception as e:
    print(f"Errore durante l'analisi: {e}")

# Install heartpy if not already installed
!pip install heartpy

import pandas as pd
import numpy as np
from scipy.signal import find_peaks, welch
from scipy.interpolate import interp1d

path_file = '230426 prova 2.csv'
fs = 200.0  # Frequenza di campionamento (200 Hz)

try:
    # Carichiamo il dataset e prendiamo solo la colonna già filtrata
    df = pd.read_csv(path_file)
    signal_data = df['Final_Result'].values

    # 2. RICERCA PICCHI E INTERVALLI
    # distance=60 significa che tra un battito e l'altro ci devono
    # essere almeno 0.3 secondi (max 200 BPM)
    picchi, _ = find_peaks(signal_data, distance=int(fs * 0.3))

    # Calcoliamo gli intervalli RR in millisecondi
    rr_intervals = np.diff(picchi) * (1000.0 / fs)

    # Asse del tempo dei picchi in secondi
    time_peaks = picchi[1:] / fs

    # 3. INTERPOLAZIONE E TRASFORMATA
    # Creiamo un segnale spaziatura temporale fissa a 4 Hz
    fs_interp = 4.0
    interp_func = interp1d(time_peaks, rr_intervals, kind='cubic')

    # Nuovo asse del tempo
    time_interp = np.arange(time_peaks[0], time_peaks[-1], 1/fs_interp)
    rr_interp = interp_func(time_interp)

    # Calcolo della Densità Spettrale (Welch)
    frequenze, potenze = welch(rr_interp, fs=fs_interp, nperseg=256)

    # 4. CALCOLO AREE LF E HF
    # Filtriamo matematicamente le bande standard
    cond_lf = (frequenze >= 0.04) & (frequenze < 0.15)
    cond_hf = (frequenze >= 0.15) & (frequenze < 0.40)

    # Integriamo (calcoliamo l'area sotto la curva) per trovare la potenza
    lf = np.trapz(potenze[cond_lf], frequenze[cond_lf])
    hf = np.trapz(potenze[cond_hf], frequenze[cond_hf])

    # Calcolo rapporto
    lf_hf_ratio = lf / hf

    print("ESTRAZIONE FREQUENZE")
    print(f"File analizzato:  {path_file}")
    print(f"LF (Low Freq):    {lf:.2f} ms²")
    print(f"HF (High Freq):   {hf:.2f} ms²")
    print(f"Rapporto LF/HF:   {lf_hf_ratio:.2f}")

except FileNotFoundError:
    print(f"Errore: Il file '{path_file}' non è stato trovato. Verifica di averlo caricato su Colab.")
except KeyError:
    print("Errore: La colonna 'Final_Result' non esiste in questo CSV. Controlla il nome della colonna.")
except Exception as e:
    print(f"Errore imprevisto durante l'analisi: {e}")

import pandas as pd
import numpy as np
from scipy.interpolate import interp1d
from scipy.signal import welch, find_peaks

# 1. Caricamento dati
df = pd.read_csv('230426 prova 2.csv')
signal = df['Final_Result'].values
fs = 200.0  # Frequenza di campionamento

# 2. Rilevamento dei picchi (Semplice Peak Detection)
# Nota: Su segnali sporchi da Pulse Sensor, questo è il punto più critico.
distance = fs * 0.6  # Assumiamo max 100 BPM (distanza minima tra picchi)
peaks, _ = find_peaks(signal, distance=distance, height=np.mean(signal))

# 3. Calcolo intervalli RR (in millisecondi)
rr_intervals = np.diff(peaks) / fs * 1000.0
# Tempo in secondi a cui corrispondono i battiti
rr_times = np.cumsum(rr_intervals) / 1000.0

# 4. Interpolazione
# I battiti sono irregolari, per la PSD serve un segnale equispaziato
fs_interp = 4  # 4Hz è lo standard per l'HRV
f_interp = interp1d(rr_times, rr_intervals, kind='cubic')
t_new = np.arange(rr_times[0], rr_times[-1], 1/fs_interp)
rr_resampled = f_interp(t_new)

# 5. Calcolo della Power Spectral Density (Metodo di Welch)
freqs, psd = welch(rr_resampled, fs=fs_interp, nperseg=len(rr_resampled))

# 6. Definizione Bande e Calcolo Aree
# Bande standard: LF (0.04 - 0.15 Hz), HF (0.15 - 0.4 Hz)
lf_mask = (freqs >= 0.04) & (freqs <= 0.15)
hf_mask = (freqs >= 0.15) & (freqs <= 0.4)

lf_power = np.trapz(psd[lf_mask], freqs[lf_mask])
hf_power = np.trapz(psd[hf_mask], freqs[hf_mask])

lf_hf_ratio = lf_power / hf_power

print(f"Potenza LF: {lf_power:.2f} ms²")
print(f"Potenza HF: {hf_power:.2f} ms²")
print(f"Rapporto LF/HF: {lf_hf_ratio:.2f}")

import pandas as pd
import numpy as np
from scipy.signal import find_peaks, welch
from scipy.interpolate import interp1d

path_file = '230426 prova 4.csv'
fs = 200.0  # Frequenza di campionamento (200 Hz)

try:
    # 1. CARICAMENTO DATI
    df = pd.read_csv(path_file)
    signal_data = df['Final_Result'].values

    # 2. RICERCA PICCHI E INTERVALLI
    # distance=int(fs * 0.3) -> permette battiti fino a 200 BPM per non perdere picchi reali
    # height=np.mean(signal_data) -> ignora il rumore di fondo sotto la media del segnale
    picchi, _ = find_peaks(signal_data, distance=int(fs * 0.3), height=np.mean(signal_data))

    # Calcoliamo gli intervalli RR in millisecondi
    rr_intervals = np.diff(picchi) * (1000.0 / fs)

    # Asse del tempo dei picchi in secondi
    time_peaks = picchi[1:] / fs

    # 3. INTERPOLAZIONE E TRASFORMATA
    # Creiamo un segnale con spaziatura temporale fissa a 4 Hz (Standard HRV)
    fs_interp = 4.0
    interp_func = interp1d(time_peaks, rr_intervals, kind='cubic')

    # Nuovo asse del tempo
    time_interp = np.arange(time_peaks[0], time_peaks[-1], 1/fs_interp)
    rr_interp = interp_func(time_interp)

    # Calcolo della Densità Spettrale (Metodo di Welch)
    # nperseg=256 su 4Hz crea "finestre" di 64 secondi. Rende i dati molto stabili.
    frequenze, potenze = welch(rr_interp, fs=fs_interp, nperseg=256)

    # 4. CALCOLO AREE LF E HF
    # Filtriamo matematicamente le bande standard HRV
    cond_lf = (frequenze >= 0.04) & (frequenze < 0.15)
    cond_hf = (frequenze >= 0.15) & (frequenze < 0.40)

    # Integriamo (calcoliamo l'area sotto la curva) per trovare la potenza assoluta
    lf = np.trapz(potenze[cond_lf], frequenze[cond_lf])
    hf = np.trapz(potenze[cond_hf], frequenze[cond_hf])

    # Calcolo rapporto simpato-vagale
    lf_hf_ratio = lf / hf

    # STAMPA RISULTATI
    print("ESTRAZIONE FREQUENZE (Versione Ottimizzata)")
    print(f"File analizzato:  {path_file}")
    print(f"LF (Low Freq):    {lf:.2f} ms²")
    print(f"HF (High Freq):   {hf:.2f} ms²")
    print(f"Rapporto LF/HF:   {lf_hf_ratio:.2f}")

except FileNotFoundError:
    print(f"Errore: Il file '{path_file}' non è stato trovato. Verifica il percorso o l'upload.")
except KeyError:
    print("Errore: La colonna 'Final_Result' non esiste in questo CSV. Controlla i nomi delle colonne.")
except Exception as e:
    print(f"Errore imprevisto durante l'analisi: {e}")